apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflow-cd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dag
    repoURL: https://github.com/AyushSoni-7/argocd-with-workflow.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

