apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-namespace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: workflows
    repoURL: https://github.com/AyushSoni-7/argocd-with-workflow.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

