apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      valueFiles:
      - values-secret.yaml
    path: manifest/secrets
    repoURL: https://github.com/AyushSoni-7/argocd-with-workflow.git
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
