apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: dag-deploy-app-test
  namespace: argocd
spec:
  serviceAccountName: workflow-pod-sa
  entrypoint: deploy-app
  templates:
  - name: k8s
    inputs:
      artifacts:
      - name: git-clone
        path: /src
        git:
          repo: https://github.com/AyushSoni-7/argocd-with-workflow.git
      parameters:
      - name: file_path
      - name: file_name
    container:
      image: bitnami/kubectl:latest
      command: [bash, -c]
      args:
      - kubectl apply -f {{inputs.parameters.file_name}}
      workingDir: "{{inputs.parameters.file_path}}"
  - name: get-pods
    container:
      image: bitnami/kubectl:latest
      command: [bash, -c]
      args:
      - kubectl get pods -n argocd
  - name: deploy-app
    dag:
      tasks:
      - name: deploy-namespace
        template: k8s
        arguments:
          parameters:
          - name: file_path
            value: /src/argocd-application
          - name: file_name
            value: namespace.yaml
      - name: deploy-configmap
        dependencies: [deploy-namespace]
        template: k8s
        arguments:
          parameters:
          - name: file_path
            value: /src/argocd-application
          - name: file_name
            value: configmap.yaml
      - name: deploy-secret
        dependencies: [deploy-namespace]
        template: k8s
        arguments:
          parameters:
          - name: file_path
            value: /src/argocd-application
          - name: file_name
            value: secret.yaml
      - name: pods
        dependencies: [deploy-configmap, deploy-secret]
        template: get-pods

