apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: argo-workflow-server-nodeport
  namespace: argo
spec:
  ports:
  - port: 2746
    protocol: TCP
    targetPort: 2746
    nodePort: 30084
  selector:
    app: argo-workflow-server
  type: NodePort
status:
  loadBalancer: {}
