apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: workflow-pod-role-binding
subjects:
- kind: ServiceAccount
  name: workflow-pod-sa
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: workflow-pod-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: workflow-pod-role
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - watch
  - list
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-pod-sa
  namespace: argocd
